### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by isvktt** [Jesewe/RadarHack#1]
update the source pls

**Comment by Jesewe** [comment]
> 

The code was created back in 2021. It's been fixed now

**Comment by isvktt** [comment]
add me in discord : isv#5460

**Comment by isvktt** [comment]
File "radarhack.py", line 9, in <module>
address = client.lpBaseOfDll + re.search(rb'\x83\xE0\x0F\x80\xBF',
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by isvktt** [comment]
fixed the code bro, i like your radar

**Comment by Jesewe** [comment]
The code has been fixed!
